<?php
/**
* English file for plugin tagger
*
* @package wolf
* @subpackage tagger
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
	/** TaggerController.php */ 
	'Tag has not been added. Name must be unique!' => 'Tag has not been added. Name must be unique!', 
	'Tag has been added!' => 'Tag has been added!', 
	'Tag not found!' => 'Tag not found!', 
	'The settings have been updated.' => 'The settings have been updated.', 
	'An error has occured.' => 'An error has occured.', 
	'Nothing was deleted!' => 'Nothing was deleted!', 
	'Page not found!' => 'Page not found!', 
	/** disable.php */ 
	'Tagger: Successfully disabled plugin.' => 'Tagger: Successfully disabled plugin.', 
	/** enable.php */ 
	'Tagger: Plugin was successfully enabled!' => 'Tagger: Plugin was successfully enabled!', 
	/** index.php */ 
	'Tagger' => 'Tagger', 
	'Add tags to any page and organize your website.' => 'Add tags to any page and organize your website.', 
	'and' => 'and', 
	/** uninstall.php */ 
	'Tagger: Unable to remove plugin settings.' => 'Tagger: Unable to remove plugin settings.', 
	'Tagger: Successfully removed plugin settings.' => 'Tagger: Successfully removed plugin settings.', 
	/** models/Tagger.php */ 
	'Purge & Recount Complete!' => 'Purge & Recount Complete!', 
	/** views/edit.php */ 
	'Name' => 'Name', 
	'Save' => 'Save', 
	'Save and Continue Editing' => 'Save and Continue Editing', 
	'or' => 'or', 
	'Cancel' => 'Cancel', 
	/** views/index.php */ 
	'Tags' => 'Tags', 
	'tagged:' => 'tagged:', 
	'Are you sure you wish to delete' => 'Are you sure you wish to delete', 
	/** views/purge.php */ 
	'Tagger Plugin' => 'Tagger Plugin', 
	'Tagger Purge & Recount Function' => 'Tagger Purge & Recount Function', 
	'Purge & Recount' => 'Purge & Recount', 
	'This action will purge all tags with a zero count from the database.  It will also recount all non-zero tags and input a fresh count.  If you wish to continue, please click the button below.  Otherwise leave this page to cancel.' => 'This action will purge all tags with a zero count from the database.  It will also recount all non-zero tags and input a fresh count.  If you wish to continue, please click the button below.  Otherwise leave this page to cancel.', 
	/** views/settings.php */ 
	'Tagger Frontend settings' => 'Tagger Frontend settings', 
	'Type Case' => 'Type Case', 
	'Uppercase' => 'Uppercase', 
	'Lowercase' => 'Lowercase', 
	'Choose if you want your tags to be uppercase. Otherwise, they will be lowercase.' => 'Choose if you want your tags to be uppercase. Otherwise, they will be lowercase.', 
	'Tag Type' => 'Tag Type', 
	'Count' => 'Count', 
	'Cloud' => 'Cloud', 
	'List' => 'List', 
	'Tagger Backend settings' => 'Tagger Backend settings', 
	'Tags per page' => 'Tags per page', 
	'Sets the number of tags to be displayed per page in the backend.' => 'Sets the number of tags to be displayed per page in the backend.', 
	'Sort Field' => 'Sort Field', 
	'Choose the field your would like your tags to be sorted by in the backend.' => 'Choose the field your would like your tags to be sorted by in the backend.', 
	'Sort Order' => 'Sort Order', 
	'ASC' => 'ASC', 
	'DESC' => 'DESC', 
	/** views/sidebar.php */ 
	'New Tag' => 'New Tag', 
	'Settings' => 'Settings', 
	'Documentation' => 'Documentation', 
	'Tutorials' => 'Tutorials', 
	'What is a Tag?' => 'What is a Tag?', 
	'Tags are generally used to organise content.' => 'Tags are generally used to organise content.', 
	'How to use Tagger?' => 'How to use Tagger?', 
	'You can add Tags to your pages by including this snippet into the page which you want the tags to appear.' => 'You can add Tags to your pages by including this snippet into the page which you want the tags to appear.', 
	/** views/view.php */ 
	/** views/documentation/index.php */ 
	'Table of Contents' => 'Table of Contents', 
	'Override Tagger Settings' => 'Override Tagger Settings', 
	'Tag Links' => 'Tag Links', 
	'or you can use:' => 'or you can use:', 
	'Tagger is configurable. Set parameters by editing Snippets->tags and changing the following valid parameters.  All of the options below are optional.' => 'Tagger is configurable. Set parameters by editing Snippets->tags and changing the following valid parameters.  All of the options below are optional.', 
	'If you would like to have the default tags, that appear in the archives just before clicking a page link, show up as links, please edit your archive and change the line that says:' => 'If you would like to have the default tags, that appear in the archives just before clicking a page link, show up as links, please edit your archive and change the line that says:', 
	'to be:' => 'to be:', 
	'The new Tag Links function give you the flexibility to be able to change a second parameter to the delimites you wish, so you could have' => 'The new Tag Links function give you the flexibility to be able to change a second parameter to the delimites you wish, so you could have', 
	'The second parameter is not required as this will default to a comma and NULL if you choose not to set it.' => 'The second parameter is not required as this will default to a comma and NULL if you choose not to set it.', 
	/** views/documentation/main.php */ 
	'Tagger: Documentation' => 'Tagger: Documentation', 
	/** views/documentation/tutorials.php */ 
	'Here we will give some examples of how Tagger can be used to achieve different scenarios on your website. Coming Soon...' => 'Here we will give some examples of how Tagger can be used to achieve different scenarios on your website. Coming Soon...', 
);